---

repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.3.0
   hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: fix-byte-order-marker
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: detect-private-key
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: end-of-file-fixer

 - repo: https://github.com/Lucas-C/pre-commit-hooks
   rev: v1.3.1
   hooks:
    - id: remove-crlf
    - id: forbid-crlf
